# Generated by Django 4.1.4 on 2022-12-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='hall',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
